name: deploy

on: [push]

jobs:
  build-and-deploy:
    env:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set branch name
        run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}
      - name: Echo branch name
        run: echo ${BRANCH_NAME}
      - name: env
        run: echo ${ACCESS_KEY_ID}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npm.taobao.org/
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run upload:oss
